# Generated by Django 3.1.1 on 2020-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='plan',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
