# Generated by Django 3.1.1 on 2020-09-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patient_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='levels',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
