# Generated by Django 3.1.1 on 2020-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='levels',
            field=models.FloatField(),
        ),
    ]
