# Generated by Django 3.1.1 on 2020-09-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200915_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='levels',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
