# Generated by Django 3.1.1 on 2020-09-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200915_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='levels',
        ),
        migrations.AddField(
            model_name='patient',
            name='medical',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
    ]
