# Generated by Django 3.1.1 on 2020-09-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200918_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='total',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
    ]
