# Generated by Django 3.1.1 on 2020-09-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_patient_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medical',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment',
            field=models.IntegerField(),
        ),
    ]
