# Generated by Django 3.1.1 on 2020-09-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_patient_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='blood',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency',
            field=models.CharField(default='q', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='town',
            field=models.CharField(default='a', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='zipcode',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
    ]
